// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eecizjerukaxwqwgcker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlY2l6amVydWtheHdxd2dja2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzc5OTIsImV4cCI6MjA2Njk1Mzk5Mn0.xhtN5eVrz-tJRrWijDuPOPivcfsM3hwpMbFyr3lPzKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});